local auria_wheel = require("auria_wheel.main")
local DewOutfits = require("DewOutfits")
local page = auria_wheel:newPage():setTitle("Test")
DewOutfits.addAction(page)
auria_wheel.setPage(page)
vanilla_model.PLAYER:setVisible(false)
